spring.application.name=quizmaster

# Check database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/quizmaster
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak Configuration
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=quizmaster-realm
keycloak.resource=quizmaster-client
keycloak.credentials.secret=6j7IPUr9OuF4xOzlmJZHgSG38ogqwhKr

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
